# Example T2 west.yml, using manifest imports.
manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: mmuenn
      url-base: https://github.com/mmuenn
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import: west.yml
    #- name: arducam-driver-zephyr
    #  remote: mmuenn
    #  revision: main
    #      path: app/arducam
  self:
    path: zapdos
